### ISSUE TITLE
multicluster-scheduler-agent pod in status ContainerCreating

### ISSUE THREAD

**Issue by XiangLi0619** [admiraltyio/multicluster-scheduler#14]
I checked the details and found the reason that secret "remote" was not found. 

Events:
  Type     Reason       Age                From                     Message
  ----     ------       ----               ----                     -------
  Normal   Scheduled    46s                default-scheduler        Successfully assigned ms/multicluster-scheduler-agent-7d65d8b586-jlrbb to node1
  Warning  FailedMount  14s (x7 over 45s)  kubelet, node1  MountVolume.SetUp failed for volume 
"remote" : secret "remote" not found

**Comment by XiangLi0619** [comment]
The pod multicluster-scheduler-agent is scheduled automatically to a normal node rather than a master node, is that right?

**Comment by adrienjt** [comment]
"remote" is the secret created in each member cluster by this step of the getting started guide:
```sh
./kubemcsa export --context $CLUSTER1 c1 --as remote | kubectl --context $CLUSTER1 apply -f -
./kubemcsa export --context $CLUSTER1 c2 --as remote | kubectl --context $CLUSTER2 apply -f -
```

It looks like you've decided to install multicluster-scheduler in the "ms" namespace, so you may need to add `--namespace ms` to the `kubectl apply` commands.

By default, we don't enforce any scheduling constraint on the agent pods, because that wouldn't work for everyone. That being said, feel free to set something under `agent.nodeSelector`, `scheduler.nodeSelector` and `webhook.nodeSelector` in your `values.yaml`.

**Comment by XiangLi0619** [comment]
> "remote" is the secret created in each member cluster by this step of the getting started guide:
> 
> ```shell
> ./kubemcsa export --context $CLUSTER1 c1 --as remote | kubectl --context $CLUSTER1 apply -f -
> ./kubemcsa export --context $CLUSTER1 c2 --as remote | kubectl --context $CLUSTER2 apply -f -
> ```
> 
> It looks like you've decided to install multicluster-scheduler in the "ms" namespace, so you may need to add `--namespace ms` to the `kubectl apply` commands.
> 
> By default, we don't enforce any scheduling constraint on the agent pods, because that wouldn't work for everyone. That being said, feel free to set something under `agent.nodeSelector`, `scheduler.nodeSelector` and `webhook.nodeSelector` in your `values.yaml`.

Thanks! It works, but after this step it still takes time for the pod to start again.

**Comment by adrienjt** [comment]
I'm glad it works now. The time it takes for the pod to restart depends on how old the pod is, because it backs off exponentially as long as the secret to mount doesn't exist. From your message above, you can see that there was seven attempts in the first 45 seconds, but likely less and less thereafter.
