### ISSUE TITLE
candidate-scheduler and proxy-scheduler: Forbidden: cannot list resource "csinodes"

### ISSUE THREAD

**Issue by buzzsurfr** [admiraltyio/multicluster-scheduler#19]
I'm not able to schedule pods across clusters using v0.8.0.

After deploying v0.8.0 using helm to 3 clusters, I'm seeing the following error in proxy-scheduler and candidate-scheduler:

```
E0507 13:29:58.249696       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.CSINode: csinodes.storage.k8s.io is forbidden: User "system:serviceaccount:admiralty:multicluster-scheduler" cannot list resource "csinodes" in API group "storage.k8s.io" at the cluster scope
```

Following online guidance, I tried adding the following lines to the **multicluster-scheduler** ClusterRole:

```yaml
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - watch
  - list
  - get
```

After applying to the cluster, I now see the following error message (again in proxy-scheduler and candidate-scheduler).

```
E0507 13:25:51.759485       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.CSINode: the server could not find the requested resource
```

### Environment ###
**Kubernetes Version:** version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
**Cloud:** AWS (EKS)
**Helm chart/version:** v0.8.0

**Comment by adrienjt** [comment]
Hi @buzzsurfr, the current release of multicluster-scheduler (v0.8.0) requires Kubernetes v1.17 or v1.18, because it uses the scheduler framework (TODO @adrienjt add this requirement to the readme). If you're stuck with v1.15, e.g., on EKS, there's a hack to make it work:

1. fork Kubernetes,
1. disable the CSINode feature gate in code (cannot be disabled at runtime because it is locked in code),
1. add a nil check where the csiNodeLister is referenced in the CSI volume predicate,
1. replace k8s.io/kubernetes with your fork in multicluster-scheduler's go.mod,
1. build and push your own image to your own registry,
1. use that image in your Helm release's values.

We might publish this image as a convenience, but we don't plan to maintain the fork in the open.
